---
- name: my test playbook
  hosts: all
  become: true
  tasks: 
  - name: install httpd packege
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start service
    service: 
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"
