---
- name: install httpd
  hosts: all
  become: yes
  tasks:
  - name: instll httpd pckage
    yum:
     name:  httpd
     state: installed

  - name: start service 
    service:
      name: httpd
      state: started

  
